### ISSUE TITLE
Troubles with "make windows"

### ISSUE THREAD

**Issue by PaulHaeger** [mruby-zest/mruby-zest-build#20]
I was investigating the build-mingw64.sh in the zyn-fusion build repo and fixing all the errors that came up. I have been succesful so far. However when running "make windows"  in mruby-zest-build I get the following error:

    C:/msys64/home/Paul/zyn-fusion-build/mruby-zest-build/deps/mruby-process/src/process.c:14:10:   fatal error: sys/wait.h: No such file or directory
    14 | #include <sys/wait.h>
    |          ^~~~~~~~~~~~

I attached the full output of the make command.
[log.txt](https://github.com/mruby-zest/mruby-zest-build/files/3769324/log.txt)

The error probably comes from the usage of the wait() function, which does not exist in windows. If there is no way to solve the problem in mruby-zest, then the build system probably needs to be switched to cygwin.

I apologize if that is not the correct repo to ask about.

**Comment by fundamental** [comment]
If memory serves correctly https://github.com/zynaddsubfx/zyn-fusion-build/blob/master/mruby-dir-glob-no-process.patch is the patch which fixes the dependency from mruby-dir-glob which removes the runtime dependency on mruby-process which allows the windows build to complete (with respect to this particular error). That change should be ported upstream at some point, however it will likely require the mruby-zest project to take over the mruby-dir-glob package as it seems to be abandoned https://github.com/gromnitsky/mruby-dir-glob/issues/1

**Comment by PaulHaeger** [comment]
Thanks for the quick response!

With a bit of fiddling I managed to install the `mruby-dir-glob-no-process.patch` and the `mruby-io-libname.patch`, however I fail at installing the `mruby-float-patch.patch`.

I attached the output, but im not sure if its any use to you. 
[log.txt](https://github.com/mruby-zest/mruby-zest-build/files/3773610/log.txt)

I apologize that its in german, I was not able to change it to english. It seems like git tries to find the code in the source files and fails.

**Comment by fundamental** [comment]
So, the patch was originally written for an older version of the mruby interpreter. I haven't had a chance to update it, though it should be a fairly straightforward process of tweaking the patch based upon the newer mruby code version. Ideally that patch would be two pieces, one for storing the backtraces and one for fixing the mingw environment floating point constants, though that's a much more minor issue.

**Comment by ZLau92** [comment]
I managed to get the original patch to apply to an old copy of mruby, but it didn't fix the sys/wait.h error on compile.

All the same, I did go through and update the backtrace file according to the old patch. Result attached.
[mruby-float-patch.zip](https://github.com/zynaddsubfx/zyn-fusion-build/files/3873092/mruby-float-patch.zip)

I was able to get zyn-fusion to build by removing the mruby-process submodule from mruby-zest-build. But it gives me a blank black window when I start it.
Not too knowledgeable about mruby, so I'm not sure how to approach. But it would seem that something about the mruby-process dependency would need to change because the sys/wait.h include file can't be satisfied by a mingw build environment.
But I'd be happy to know if a workaround exists :-)

**Comment by justnope** [comment]
The black window should be fixed with PR #30

**Comment by fundamental** [comment]
If it's not fixed, feel free to reopen.

**Comment by AnClark** [comment]
Maybe replacing mruby-process with [appPlant's edition](https://github.com/appPlant/mruby-process) would help. It can cross-compile under my Arch Linux environment.

**Comment by fundamental** [comment]
Off the top of my head I can't recall if the process gem is even needed
anymore. Early on in the development of the GUI it was certainly used to
spawn off other subtasks, but I had thought that code was removed at this
stage...

**Comment by AnClark** [comment]
So having a re-check of the source files may be necessary.  Or instead, merely replacing mruby-process repo in `.gitmodules` is also a good choice.
Currently I don't touch it in my Makefile. I just merely "polyfill" with a Makefile recipe: remove `deps/mruby-process`, then clone appPlant's edition there.
