### ISSUE TITLE
Not able to build Zyn-fusion (AUR).

### ISSUE THREAD

**Issue by apoorv569** [mruby-zest/mruby-zest-build#26]
I'm trying to build zyn-fusion from the AUR, but it fails after some time and gives this output

`ar: creating /home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/build/host-debug/lib/libmruby.a
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/Rakefile:45: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/lib/ruby/2.7.0/fileutils.rb:595: warning: The called method `rm_f' is defined here
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/Rakefile:46: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/lib/ruby/2.7.0/fileutils.rb:426: warning: The called method `cp' is defined here
CC    mrbgems/mruby-bin-mruby/tools/mruby/mruby.c -> build/host/mrbgems/mruby-bin-mruby/tools/mruby/mruby.o
LD    build/host/bin/mruby 
/usr/bin/ld: /home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/build/host/lib/libmruby.a(nvg_context.o):(.data.rel.ro.local+0x0): multiple definition of `mrb_nvg_context_type'; /home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/build/host/lib/libmruby.a(gem.o):/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/src/gem.c:293: first defined here
collect2: error: ld returned 1 exit status
/usr/bin/ld: /home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/build/host/lib/libmruby.a(nvg_context.o):(.data.rel.ro.local+0x0): multiple definition of `mrb_nvg_context_type'; /home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/build/host/lib/libmruby.a(gem.o):/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/src/gem.c:293: first defined here
collect2: error: ld returned 1 exit status
rake aborted!
Command failed with status (1): [gcc -Wl,-O1,--sort-common,--as-needed,-z,r...]
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:31:in `_run'
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:36:in `rescue in _run'
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:32:in `_run'
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:183:in `run'
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/Rakefile:72:in `block (4 levels) in <top (required)>'

Caused by:
Command failed with status (1): ["gcc" -Wl,-O1,--sort-common,--as-needed,-z...]
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:33:in `_run'
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:183:in `run'
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/Rakefile:72:in `block (4 levels) in <top (required)>'
Tasks: TOP => default => all => /home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/bin/mruby => /home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/build/host/bin/mruby
(See full trace by running task with --trace)
make: *** [Makefile:13: all] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
Error making: zyn-fusion
`
please help, as i really in need for this plugin my projects depends on this plugin.

**Comment by fundamental** [comment]
Dup of #25
