### ISSUE TITLE
Dev Question: Is there a method to update Zest UI according to VST FX's state?

### ISSUE THREAD

**Issue by AnClark** [mruby-zest/mruby-zest-build#35]
## Preface

I come about this issue when I'm using ZynAddSubFX under REAPER. 

DAWs like REAPER support saving VST's **state** as so-called "user presets" (or directly saving it into project file). And in most VST plugins, when you load a "user preset", the state (aka. configurations) of that plugin is restored, and **the UI is also updated according to the state**. For example, when you load a state for Dragonfly Reverb, all the knobs will point to where you've configured at that time.

However, currently ZynAddSubFX cannot do this whatever the UI module I use (Zest or NTK). It can still load state, but the UI  still keeps unchanged, not showing my manually-configured parameters. This will be great trouble to DAW users.

## My thoughts

**DFP has a method `DISTHRO::UI.stateChanged()`**, which is to be implemented in `zynaddsubfx/src/Plugin/ZynAddSubFX/ZynAddSubFX-UI-Zest.cpp`:

```c++
   /**
      A state has changed on the plugin side.
      This is called by the host to inform the UI about state changes.
    */
    void stateChanged(const char* key, const char* value) override
    {
    }
```

I've tested that on these situations REAPER will call this method:
- When I change "user presets";
- When plugin UI reloads.

So **I want to invoke a method to manually (or forcibly) update Zest UI in `stateChanged()`**. But I cannot find any APIs  related to it. I also want to write one myself, but I cannot figure out how Zest updates its UI, since inner routines in both Zest and ZynAddSubFX are hard to comprehend.

## Moreover: What's the routine behind a click on Zest's bank view?

I find that when I choose a preset in Zest's bank view, it can automatically load that preset into synthesizer, then update UI correspondingly. But the inner routine is complicated, and almost unable for me to know.

Here's my partial researches to the source code:

1. According to `mruby-zest/examples/ZynBanks.qml`, when I choose a bank, it invokes `doBank()`, then send a OSC message to ZynAddSubFX:

```ruby
    function doLoad()
    {
        ins = ins_sel.selected_val
        part = root.get_view_pos(:part)
        return if part.class != Fixnum
        $remote.action("/load_xiz", part, ins) if !ins.empty?
        $remote.damage("/part#{part}/");
    }
```

2. On ZynAddSubFX's side, this is how the OSC path `/load_xiz` registers (`zynaddsubfx/src/Misc/MiddleWare.cpp:1591`):

```c++
    {"load_xiz:is", 0, 0,
        rBegin;
        const int part_id = rtosc_argument(msg,0).i;
        const char *file  = rtosc_argument(msg,1).s;
        impl.pending_load[part_id]++;
        impl.loadPart(part_id, file, impl.master, d);
        rEnd},
```

3. Look into `impl.loadPart()`, it finally transmit another OSC message `/load-part:ib` (`zynaddsubfx/src/Misc/MiddleWare.cpp:568`).

```c++
        //Give it to the backend and wait for the old part to return for
        //deallocation
        parent->transmitMsg("/load-part", "ib", npart, sizeof(Part*), &p);
        d.broadcast("/damage", "s", ("/part"+to_s(npart)+"/").c_str());
```

4. Here's the definition of `/load-part:ib` (`zynaddsubfx/src/Misc/Master.cpp:431`). I tried to comment some lines, and noted down  corresponding consequences:

```c++
    {"load-part:ib", rProp(internal) rDoc("Load Part From Middleware"), 0, [](const char *msg, RtData &d) {
       Master *m =  (Master*)d.obj;
       Part   *p = *(Part**)rtosc_argument(msg, 1).b.data;
       int     i = rtosc_argument(msg, 0).i;
       m->part[i]->cloneTraits(*p);        // Bypass this: Preset won't load, but Zest UI still updates
       m->part[i]->kill_rt();                     // Bypass this: No explicit consequence
       d.reply("/free", "sb", "Part", sizeof(void*), &m->part[i]);        // Bypass this: No explicit consequence
       m->part[i] = p;
       p->initialize_rt();        // Bypass this: No explicit consequence
       memset(m->activeNotes, 0, sizeof(m->activeNotes));
       }},

```

By the end of here, I got puzzled. I still cannot know where Zest updates its UI.

**Comment by fundamental** [comment]
> So I want to invoke a method to manually (or forcibly) update Zest UI in stateChanged(). But I cannot find any APIs related to it. I also want to write one myself, but I cannot figure out how Zest updates its UI, since inner routines in both Zest and ZynAddSubFX are hard to comprehend.

I was under the impression that this was handled behind the scenes already, but perhaps not.
So, Zyn has a lot of parameters, much more than is typical for a normal VST plugin. As such it doesn't expose the parameters directly to the host, same thing with overall program state. The only things the host sees are the automation ports and a read only bit of information about the OSC port. When the plugin saves it stores all of the overall state in an xml blob which it then can hand back to the plugin host. When the state is provided to load the system what should happen is:

1) Plugin host says "please load up yourself from this buffer"
2) Zyn internally casts that back to a long string representing some XML
3) The non-realtime worker thread within zyn, aka 'middleware', takes that and creates a new master synth runtime object.
4) The new master synth instance is passed over to the realtime side to swap with the old one.
5) The system emits a message to any user interface saying "Hey, there's been a massive state change, please consider basically any information you had as out-of-date"
6) The GUI starts spamming out requests for new parameters to display to the user.

**Comment by fundamental** [comment]
> I find that when I choose a preset in Zest's bank view, it can automatically load that preset into synthesizer, then update UI correspondingly. But the inner routine is complicated, and almost unable for me to know.

Rephrasing the steps that you see:
1a) The GUI says "please load instrument X to part Y"
1b) The GUI says "hey any information that we have on parameters starting with /partY/ are likely out-of-date"
2) The non-realtime worker thread gets to load data from the file system (simpler VST get to skip some of this)
3a) The non-realtime worker thread sends the loaded data over to the realtime side where synthesis actually happens
3b) The non-realtime worker thread lets any other GUI process know that any view they might have is out of date (that's all "damage" messages do)
4) The realtime side accepts the new state and sends the old state back to the worker thread to be deallocated



Let's consider a much simpler world.
Let's say each part has a volume and a waveshape.
They would be represented as /part0/volume and /part0/oscillator/waveshape. At stage 1a the GUI might know that the user had those set to +5dB and 100% sawtooth. As soon as a damage message occurs from either 1b or 3b, the GUI says "well, I know what the values used to be, but I need to ask for new values when possible". So there will be messages sent out to the audio side of things asking "what is the value of /part0/volume" and "what is the value of /part0/oscillator/waveshape". After it gets those values, they're cached until the user changes them.

**Comment by AnClark** [comment]
Thanks for your explanations! 

Next, I want to wite an API `zest_update_gui()` settled in `mruby-widget-lib/api.c`, and invoke it in DPF's `DISTHRO::UI.stateChanged()` method:

```c++
   /**
      A state has changed on the plugin side.
      This is called by the host to inform the UI about state changes.
    */
    void stateChanged(const char* key, const char* value) override
    {
        if(z.zest)
            z.zest_update.gui();
    }
```

But I don't know where are the codes related to your explanations above, and Zest's code seems complicated to me (I'm new to Ruby). Would you love to give some suggestions for me to write that API?

**Comment by fundamental** [comment]
So, for the steps you're interested in you're going to want to get access to the global "$remote" and call the "damage" method with the arguments "/" (I think). That would tell the component which works with remote values "everything is out of date". You can see the other code in api.c is calling the zest runner class. That class is defined in the unintuitively named 'script.rb' file, and within that class it should be sample enough to create a new methods in the vein of "def forget_all_state;$remote.damage("/");end" Then you would be able to call the zest runner's new forget_all_state method in a similar manner to the rest of the api.c functions.

**Comment by AnClark** [comment]
Thanks, Mark! I have finished!
Here are my commits of this improvement:
- d05c1af692b4faa0c2b99acc2af0 (mruby-zest-build)
- [Commit in ZynAddSubFX](https://github.com/AnClark/zynaddsubfx/commit/7e8e68cd5f4581d1f305f857b4136451bc144bfc)

**Comment by fundamental** [comment]
Likely a dumb question, but the modified code fixes the out-of-date parameters previously in your VST host, right?

**Comment by AnClark** [comment]
Yes. I use REAPER, and after this modification Zest now works well than before, especially when **reloading presets saved in REAPER projects**.
