### ISSUE TITLE
Cannot build without the Internet due to mruby calling git clone

### ISSUE THREAD

**Issue by fpesari** [mruby-zest/mruby-zest-build#49]
Hello,

when building mruby-zest-build without the Internet on a virtualized environment the build fails with this message

```
touch src/mruby-widget-lib/src/api.c  
cd mruby             &&  MRUBY_CONFIG=../build_config.rb rake
Environment is:

GIT   https://github.com/mruby/mgem-list.git -> build/repos/host/mgem-list
Cloning into '/home/me/mruby-zest-build-git.master.2021.05.19.fix/mruby/build/repos/host/mgem-list'...
fatal: unable to access 'https://github.com/mruby/mgem-list.git/': Couldn't connect to server
```

Ideally, also for improved security, the build should not connect to the internet if the user building it has already cloned the repository and all its submodules.

**Comment by fundamental** [comment]
Thanks for the bug report. This is a regression as I'm fairly sure a few months back it did not access the internet at all.
